### PR TITLE
updated climberManager_initialize_State.cpp

### LINKED ISSUE #243: Climber Manager Initialize State Transition
In ClimberManager_Initialize_State.cpp

Update IsTransitionCondition() and AtTarget() methods to accomplish the state transitions below.

Conditions to Enter or stay in State:
If
In Climb Mode
Transition into state

To access robot state and check if Climb Mode is on or off use the code below
if (m_mechanism->m_climbMode== RobotStateChanges::ClimbMode::ClimbModeOff)
or
if (m_mechanism->m_climbMode== RobotStateChanges::ClimbMode::ClimbModeOn)

### PR DESCRIPTION
**Pull request by ImAPenguin56**
closes #243

### CODE REVIEW

**Comment by Tan560** [comment]
Why are you changing both the manual state and initialize states? This is supposed to be for only the initialize state transition

**Comment by ImAPenguin56** [comment]
removed the accidental changes made to the branch.

**Review by Tan560 — APPROVED** [review]

**Review by Tan560 — CHANGES_REQUESTED** [review]
Update Main and change 
m_mechanism->m_climbMode== RobotStateChanges::ClimbMode::ClimbModeOn
to 
m_mechanism->isClimbMode()

**Review by Tan560 — APPROVED** [review]
Changes as requested

**Comment by witcpalek** [comment]
please add which issue this closes and the project

**Comment by Tan560** [comment]
@witcpalek  Done, thanks

**Pull request merged**
